name: CVE Scan

on:
  push:
    branches: ["main"]
    tags: ["**"]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: "14 3 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      backend:
        image: ghcr.io/robert-koch-institut/mex-backend:1.2.0
        env:
          MEX_BACKEND_API_USER_DATABASE: ${{ secrets.MEX_BACKEND_API_USER_DATABASE }}
          MEX_BACKEND_API_KEY_DATABASE: ${{ secrets.MEX_BACKEND_API_KEY_DATABASE }}
          MEX_IDENTITY_PROVIDER: graph
          MEX_GRAPH_URL: neo4j://neo4j:7687
          MEX_DEBUG: True
        ports:
          - 8080:8080
        options: --entrypoint testing-backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Cache requirements
        uses: actions/cache@v5
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Cache environment
        uses: actions/cache@v5
        env:
          cache-name: cache-environment
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('*.lock') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install requirements
        run: make setup

      - name: Export dependencies
        run: |
          mkdir --parents pdm
          pdm export --group :all --no-hashes -f requirements > pdm/requirements.txt

      - name: Generate package-lock.json
        run: |
          pdm run reflex export --frontend-only --no-zip
          cd .web
          npm install --package-lock-only --legacy-peer-deps

      - name: Run trivy
        uses: aquasecurity/trivy-action@master
        with:
          format: 'sarif'
          list-all-pkgs: 'true'
          output: 'trivy-results.sarif'
          scan-ref: '.'
          scan-type: 'fs'
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Publish results
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
